# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: orangeshell

before:
  hooks:
    - go mod tidy

builds:
  - id: orangeshell
    binary: orangeshell
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/oarafat/orangeshell/version.version={{.Version}}
      - -X github.com/oarafat/orangeshell/version.commit={{.ShortCommit}}
      - -X github.com/oarafat/orangeshell/version.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: arafato
    name: orangeshell
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

brews:
  - name: orangeshell
    repository:
      owner: arafato
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/arafato/orangeshell"
    description: "A TUI dashboard for managing the Cloudflare Developer Platform"
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "orangeshell"
    test: |
      system "#{bin}/orangeshell", "--version"
